baseURL = 'https://msl9204.github.io/'
languageCode = 'en-us'
title = 'my site'
theme = 'paper-mod'

[menu]
[[menu.main]]
  identifier = 'archives'
  name = 'Archives'
  title = 'archives'
  url = '/archives/'
  weight = 2

[[menu.main]]
  identifier = 'about'
  name = 'About'
  title = 'about'
  url = '/about/'
  weight = 1