baseURL: https://msl9204.github.io/
languageCode: en-us
title: Tech Log
theme: paper-mod

menu:
  main:
    - identifier: archives
      name: Archives
      title: archives
      url: /archives/
      weight: 2

    - identifier: about
      name: About
      title: about
      url: /about/
      weight: 1

Params:
  disableThemeToggle: true
  defaultTheme: dark

  ShowReadingTime: true

  # 목차
  ShowToc: true
  TocOpen: false
  
  ShowBreadCrumbs: true

  ShowCodeCopyButtons: true
  
  ShowPostNavLinks: true

  comments: true
